# Site settings
name: BabyR
email: song.jehoon@gmail.com
author: Je-Hoon Song
url: https://jehoons.github.io
resume_site: https://jehoons.github.io/Resume.io/
github: https://github.com/luoyan35714/
baseurl: "https://jehoons.github.io/"
description: Actually, less is more!
meta_description: My small lab;
motto: It's our wits that make us men.
banner: Knowing is not enough, we must apply. 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/

paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jehoons 

highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    # provider : duoshuo
    # duoshuo:
    #     short_name : luoyan35714
    disqus :
        short_name : jehoons
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light