---
title: Jehoons.Github.Io
plugins:
  - jekyll-seo-tag
timezone: Asia/Seoul
future: true
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: BabyR
description: Baby Researcher
avatar: https://github.com/jehoons/jehoons.github.io/blob/master/images/jekyll-logo.png?raw=true
footer-links:
  dribbble: 
  email: song.jehoon@gmail.com
  facebook: 
  flickr: 
  github: jehoons
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: JeHoonSong1
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: jehoons
google_analytics: 
url: http://jehoons.github.io
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
